config/routes.rb
Rails.application.routes.draw do

  resources :channels
  root 'discussions#index'

  # Nested replies inside discussions
  resources :discussions do
    resources :replies, constraints: {onlyajax: true}
  end
  devise_for :users, controllers: { registrations: 'registrations'}

  # route for volunteers home page
  get "volunteer", to: "home#volunteer", as: :volunteer
  get "home", to: "home#index", as: :home_index
  get "admin", to: "home#admin", as: :admin
  get "volunteer_list", to: "home#volunteer_list", as: :volunteer_list
  get "twitter", to: "home#twitter", as: :twitter
  get "policy", to: "home#policy", as: :policy
  get "contact", to: "home#contact", as: :contact

  #post request for contact form
  post 'request_contact', to: 'home#request_contact'

  #report routes
  resources :reports, :only => [:index, :create]
  get "reports/reply", to: "reports#show_reply"
  get "reports/discussion", to: "reports#show_discussion"
  patch "reports", to: "reports#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route to the volunteer questionnaire
  get "questionnaire", to: "home#questionnaire"
  post "submit_questionnaire", to: "home#submit_questionnaire"

end

app/models/channel.rb
class Channel < ApplicationRecord
    # Establishing the relationship
    has_many :discussions
    has_many :users, through: :discussions

    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]

    # Method to create friendly urls
    def should_generate_new_friendly_id?
      name_changed?
    end

    #Validation
    validates :name, length: {minimum: 4, maximum: 25}
    validates :name, presence: true
    validates :name, uniqueness: { case_sensitive: false }
  end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: %i[ show edit update destroy ]

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /channels/1 or /channels/1.json
  def show
    @discussions = Discussion.where('channel_id = ?', @channel.id)
    @channels = Channel.all.order('created_at desc')
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels or /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to channels_path, notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1 or /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to channels_path, notice: "Channel was successfully updated." }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.haml
= simple_form_for(@channel) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    .field
      .control
        = f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}
  .form-actions
    = f.button :submit, class: 'button-is-info'

app/views/channels/edit.html.haml
- content_for(:html_title) { 'MHS - Edit Channel' }
%h1.title.is-3 Editing Channel
= render 'form', channel: @channel

app/views/channels/index.html.haml
- content_for(:html_title) { 'MHS - Channels' }
%p#notice= notice
%h1.title.is-2 Channels
-if admin?
  .level
    .level-left
    .level-right
      =link_to 'New Channel', new_channel_path, class: 'button is-dark'
  %table.table.is-fullwidth
    %thead
      %tr
        %th Channel
        %th{colspan: "3"}
    %tbody
      - @channels.each do |channel|
        %tr
          %td= link_to channel.name, channel
          %td
            .buttons.is-right
              = link_to 'View Channel', channel, class:'button is-info'
              = link_to 'Edit Channel', edit_channel_path(channel), class:'button is-info'
              = link_to 'Delete', channel, class:'button is-danger', method: :delete, data: { confirm: "Are you sure you want to delete this channel? " }
-else
  You don't have access to this page!

app/views/channels/new.html.haml
- content_for(:html_title) { 'MHS - New Channel' }
.columns.is-centered
  .column.is-4
    %h1.title.is-3 Create a new channel
    = render 'form', channel: @channel

app/views/channels/show.html.haml
- content_for(:html_title) { "MHS - #{@channel.name}" }
%p#notice= notice
.level
  .level-left
    %h1.title.is-2= @channel.name
%hr/
.columns
  = render 'shared/discussions'
  = render 'discussions/sidebar'