config/routes.rb
Rails.application.routes.draw do

  resources :channels
  root 'discussions#index'

  # Nested replies inside discussions
  resources :discussions do
    resources :replies, constraints: {onlyajax: true}
  end
  devise_for :users, controllers: { registrations: 'registrations'}

  # route for volunteers home page
  get "volunteer", to: "home#volunteer", as: :volunteer
  get "home", to: "home#index", as: :home_index
  get "admin", to: "home#admin", as: :admin
  get "volunteer_list", to: "home#volunteer_list", as: :volunteer_list
  get "twitter", to: "home#twitter", as: :twitter
  get "policy", to: "home#policy", as: :policy
  get "contact", to: "home#contact", as: :contact

  #post request for contact form
  post 'request_contact', to: 'home#request_contact'

  #report routes
  resources :reports, :only => [:index, :create]
  get "reports/reply", to: "reports#show_reply"
  get "reports/discussion", to: "reports#show_discussion"
  patch "reports", to: "reports#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route to the volunteer questionnaire
  get "questionnaire", to: "home#questionnaire"
  post "submit_questionnaire", to: "home#submit_questionnaire"

end

app/models/discussion.rb
class Discussion < ApplicationRecord
    # Establishing the relationship
    belongs_to :channel
    belongs_to :user
    has_many :replies, dependent: :destroy
    has_one :discussion_report, dependent: :destroy

    #validation
    validates :title, length: {minimum: 4, maximum: 25}
    validates :title, :content, :user, :channel, presence: true

    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]

    # Method to create friendly urls
    def should_generate_new_friendly_id?
      title_changed?
    end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  # List of before actions to do for the controller
  before_action :set_discussion, only: %i[ show edit update destroy ]
  before_action :find_channels, only: [:index, :show, :new, :edit, :create, :update]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /discussions or /discussions.json
  def index
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /discussions/1 or /discussions/1.json
  def show
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /discussions/new
  def new
    @discussion = current_user.discussions.build
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions or /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion was successfully created." }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1 or /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: "Discussion was successfully updated." }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1 or /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: "Discussion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    def find_channels
      @channels = Channel.all.order('created_at desc')
    end

    # Only allow a list of trusted parameters through.
    def discussion_params
      params.require(:discussion).permit(:title, :content, :channel_id)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  #Checking whether the user is signed in and whether the current signed in user is the same as the user who wrote the discussion
  #this is done by passing the discussion into the method
  def discussion_author(discussion)
    user_signed_in? && current_user.id == discussion.user_id
  end

  #checking for the replying user as to whether they are the one who wrote the reply
  def reply_author(reply)
    user_signed_in? && current_user.id == reply.user_id
  end

end

app/views/discussions/_form.html.haml
= simple_form_for(@discussion) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    .field
      .control
        = f.input :title, required: true, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}
    .field
      .control
        = f.input :content, required: true, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'}
    .field
      %label.label Channel
      .control.has-icons-left
        %span.select
          = f.input_field :channel_id, collection: @channels.map {|channel| [channel.name, channel.id]}, prompt: "Select Channel"
        %span.icon.is-small.is-left
          %i.fa.fa-tag
  .form-actions
    .field
      .control
        = f.button :submit, class:"button is-info"

app/views/discussions/_sidebar.html.haml
.column.is-3.is-offset-1
  %h3.title.is-5.has-text-gery-light Channels
  %ul.list
    - @channels.each do |channel|
      %li
        =link_to channel.name, channel
  %br
  -# admin role
  - if admin?
    = link_to 'New Channel', new_channel_path, class: 'button button is-info'

app/views/discussions/edit.html.haml
- content_for(:html_title) { 'MHS - Edit Discussion' }
%h1.title.is-3 Editing Discussion

= render 'form', discussion: @discussion

app/views/discussions/index.html.haml
.columns
  = render 'shared/discussions'
  = render 'sidebar'

app/views/discussions/new.html.haml
- content_for(:html_title) { 'MHS - New Discussion' }
%h1.title.is-3 New Discussion
= render 'form', discussion: @discussion
= link_to 'Back', discussions_path

app/views/discussions/show.html.haml
- content_for(:html_title) { "MHS - #{@discussion.title}" }
.columns
  .column.is-8
    %h1.title.is-2.discussion-title
      =@discussion.title
    %h3.subtitle.is-5.has-text-grey-lighter
      by #{@discussion.user.username} in #{link_to @discussion.channel.name, @discussion.channel}
    .content
      = markdown(@discussion.content)
    .level
      .level-left
      .level-left
        -#  check profile so that only author of discussion can edit or remove. TEST PASSED SUCCESFULLY: ONLY USERS CAN EDIT THEIR OWN COMMENT
      - if discussion_author(@discussion)
        .buttons
          =link_to 'Edit Discussion', edit_discussion_path(@discussion), class:'button button is-info is-outlined'
          =button_to 'Delete', discussion_path(@discussion), class:'button button is-info is-outlined', method:'delete' ,data: {confirm: "Are you sure?"}

        %h2.subtitle.is-5
          =@discussion.replies.count
          Replies
    #discussion-replies
      - @discussion.replies.each do |reply|
        -unless reply.parent_id
          = render reply
    %h3.subtitle.is-3 Reply
    -if user_signed_in?
      = render 'replies/form'
    -else
      %p To reply you need to
      = link_to 'Log In', new_user_session_path
      or
      =link_to 'Sign Up', new_user_registration_path
  = render 'sidebar'
-#a