config/routes.rb
Rails.application.routes.draw do

  resources :channels
  root 'discussions#index'

  # Nested replies inside discussions
  resources :discussions do
    resources :replies, constraints: {onlyajax: true}
  end
  devise_for :users, controllers: { registrations: 'registrations'}

  # route for volunteers home page
  get "volunteer", to: "home#volunteer", as: :volunteer
  get "home", to: "home#index", as: :home_index
  get "admin", to: "home#admin", as: :admin
  get "volunteer_list", to: "home#volunteer_list", as: :volunteer_list
  get "twitter", to: "home#twitter", as: :twitter
  get "policy", to: "home#policy", as: :policy
  get "contact", to: "home#contact", as: :contact

  #post request for contact form
  post 'request_contact', to: 'home#request_contact'

  #report routes
  resources :reports, :only => [:index, :create]
  get "reports/reply", to: "reports#show_reply"
  get "reports/discussion", to: "reports#show_discussion"
  patch "reports", to: "reports#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route to the volunteer questionnaire
  get "questionnaire", to: "home#questionnaire"
  post "submit_questionnaire", to: "home#submit_questionnaire"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # redirects users to the correct home controller action based on user role
  def index
  # If condition to send users to the right path
    # If user is not logged in, sends them to the root path
    if !current_user.present?
      redirect_to root_path, alert: "Please sign in to view this page"
    # If user is volunteer, sends them to the volunteer path
    elsif helpers.volunteer?
      redirect_to volunteer_path, notice: "Welcome Volunteer"
    # TODO If user is admin, sends them to the admin path
    elsif helpers.admin?
      redirect_to admin_path, notice: "Welcome Admin"
    else
      redirect_to edit_user_registration_path
    end

  end

  #Admin Account Page
  def admin
    #unless statement to check if user is an admin and if not redirects to home with an alert
    unless helpers.admin?
      redirect_to root_path, alert: "Only an admin can view this page"
    end
  end

  #Volunteer Account page
  def volunteer
    unless helpers.volunteer?
      # Alert text to let them know why they can't access the page
      redirect_to root_path, alert: "Only a volunteer can view this page"
    end

    # If they completed both questionnaire and id verificaiton, make them an volunteer
    # Maybe a btn to make the user becomecurrent_user.present? && current_user.volunteer == true a volunteer (rolifiy wise)
  end

  #Display a list of volunteers if user is admin, otherwise redirect
  def volunteer_list
    unless helpers.admin?
      redirect_to root_path, alert: "Only an admin can view this page"
    end
    @users = User.volunteer_list
  end

  #Display a page of tweets from the MHS twitter account (including retweets)
  def twitter
    # Giving a username variable and an options variable that are used as parameters for the user_timeline method
    username = 'MHS_Group21'
    options = {:count => 20, :include_rts => true, :tweet_mode => 'extended'}
    # Making a tweets variable that stores the JSON file that is received for user_timeline method
    @tweets = $client.user_timeline(username, options)

    # Method to get tweets from home timeline
    # @tweets = $client.home_timeline
  end

  #Volunteer questionaire
  def questionnaire
    if (!helpers.volunteer? || current_user.volunteer.questionaire == true || current_user.volunteer.questionaire_attempts > 3)
      # Alert text to let them know why they can't access the page
      #current_user.quiz_complete = false
      #current_user.save
      redirect_to volunteer_path, alert: "Only a user who is volunteer and hasnt completed the quiz can view this page"
    end
  end

  #controlre action
  def submit_questionnaire
    @total = Integer(params[:question1]) + Integer(params[:question2]) + Integer(params[:question3]) + Integer(params[:question4]) + Integer(params[:question5]) + Integer(params[:question6]) + Integer(params[:question7]) + Integer(params[:question8]) + Integer(params[:question9]) + Integer(params[:question10]) + Integer(params[:question11]) + Integer(params[:question12]) + Integer(params[:question13]) + Integer(params[:question14]) + Integer(params[:question15])+ Integer(params[:question16])+ Integer(params[:question17]) + Integer(params[:question18]) + Integer(params[:question19]) + Integer(params[:question20])

    if @total == 20
      flash.notice = "Well done. You have completed the volunteer training."
      current_user.volunteer.questionaire = true
      current_user.save
      redirect_to volunteer_path
    end

    if @total < 20
      #flash.alert = @total
      flash.alert = "Unfortunately you have failed the training. You can try again when you're ready."
      current_user.volunteer.questionaire_attempts += 1
      redirect_to volunteer_path
    end
  end

  def policy
  end

  def contact
  end
  #sends contact email to user
  def request_contact
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    #checks if the email or message is left blank
    if @email.blank? | @message.blank?
      #alerts user that the email or message has been left blank
      flash[:alert] = "Make sure that email and message are not left blank"
      #refreshes the page
      redirect_to request.referer
    else
      #sends the email
      ContactMailer.contact_email(@email, @name, @message).deliver
      #sends a notice that confirms that the email has been sent
      flash[:notice] = "Thank you for contacting us, we'll reply as soon as possible"
      #redirects to the home page
      redirect_to root_path
    end

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.haml
- content_for(:html_title) { 'MHS - Admin' }
%section.section
  .container
    .columns.is-centered
      .column.is-4
        %h2.title.is-2.is-spaced Admin Homepage
    %table.table.is-fullwidth
      %tr
        %th
          %p.subtitle.is-3 Volunteer List
        %th= link_to 'View', volunteer_list_path, {class: "button is-info is-rounded is-normal is-fullwidth"}
      %tr
        %th
          %p.subtitle.is-3 Channels
        %th= link_to 'View', channels_path, {class: "button is-info is-rounded is-normal is-fullwidth"}
      %tr
        %th
          %p.subtitle.is-3 Reports
        %th= link_to 'View', '', {class: "button is-info is-rounded is-normal is-fullwidth"}
      %tr
        %th
          %p.subtitle.is-3 Edit Details
        %th= link_to 'Edit', edit_user_registration_path, {class: "button is-info is-rounded is-normal is-fullwidth"}
      %tr
        %th
          %p.subtitle.is-3 Logout of the session
        %th= button_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger is-rounded is-normal is-fullwidth"

app/views/home/contact.html.haml
//%h1= "Contact page"
%section.section
  .container
    .columns.is-centered
      .column.is-5

        %div.contactPage
          %h2.title.is-2 Contact Page
          =label_tag :saying, "Please contact us if you would like to report any discussions or comments. Please include the channel name, discussion name and an optional reply. We will look into the issue within 24 hours."
          = form_tag request_contact_path, method: 'post' do

            = label_tag :name, "Name"
            = text_field_tag :name, '', title: "Enter Name", size: 50

            = label_tag :email, t('.email')
            = email_field_tag :email, '', title: "Enter email"

            = label_tag :message, t('.message')
            = text_field_tag :message, '', title: t('.enter_message'), size: 100

            = submit_tag "Contact us"

app/views/home/index.html.haml
- content_for(:html_title) { 'MHS - Home Index' }
%h1 Home#index
%p Find me in app/views/home/index.html.erb

app/views/home/policy.html.haml
- content_for(:html_title) { 'MHS - User Policy' }
%section.section
  .container
    .columns.is-centered
      .column.is-4
        %h2.title.is-2.is-spaced.has-text-centered User Policy
    %ul
      %li •	  Do not use the application to abuse or harass users.
      %li •	  Do not share personal information such as name, address, social media information or phone number on this site.
      %li •   We do not collect any personal data on our users other than emails.
      %li •	  Please contact us if you would like to report any discussions or comments. Please include the channel name, discussion name and an optional reply. We will look into the issue within 24 hours.
    .columns.is-centered
      .column.is-4
        %h2.title.is-3.is-spaced.has-text-centered Volunteer Policy
    %ul
      %li •	  We will not require qualifications for any of our volunteers, as the goal is to connect unqualified volunteers with people suffering from non-crisis mental health issues as active listeners.
      %li •	  We will not store identification documents once they have been used to verify users’ identity.
      %li •	  Identification may need to be revalidated after a certain period.
      %li •   We will not store a copy of this ID document, however we will store the full names of our volunteers once an ID is verified through Yoti
      %li •	  Volunteers will need to complete a small questionnaire on active listening skills and our policy before they can be connected to members.
      %li •	  Volunteer accounts will need to have been verified for a week before they can administrate the discussions and connect privately to members.
      %li •	  If volunteers are connected to a member in crisis, they are not to continue the conversation and must immediately refer the member to the relevant crisis line e.g. the Samaritans, Suicide Hotline.
    .columns.is-centered
      .column.is-4
        %h2.title.is-3.is-spaced.has-text-centered Member Policy
    %ul
      %li •	  This is not therapy site and is not a suitable replacement for help from medical professionals.
      %li •	  Our volunteers are not trained to handle people in crisis, if a member feels they are a harm to themselves or others they will be referred to a crisis line.
      %li •	  Some forum content may be limited/restricted if the content is found to be unsuitable or harmful to others.
      %li •	  Abusive or harmful comments may lead to member account termination. IP/Mac address may need to be blacklisted if multiple violations from different accounts are found to be from the same source.

app/views/home/questionnaire.html.haml
%section.section
  .container
    .columns.is-centered
      .column.is-7


        %h2.title.is-2 Volunteer Questionnaire
        %div.questionnaire
          = form_tag submit_questionnaire_path, name: 'questionForm', method: 'post' do

            %h.title.is-4 Policy Questions
            %div.question
              = label_tag :question1, "Question 1 - What is the goal of reflecting content?"
              %select#question1{:name => "question1", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} To listen to the speaker so you can point out any mistakes that the speaker has made
                %option{:value => 1} To listen to the speaker and show that you are listening by drawing out more of the speaker's story
                %option{:value => 0} To memorize the speaker's story

            %div.question
              = label_tag :question2, "Question 2 - Which one of the following is an open-ended question?"
              %select#question2{:name => "question2", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 1} How are you feeling?
                %option{:value => 0} Do you still feel sad today?
                %option{:value => 0} Should you say that to her?

            %div.question
              = label_tag :question3, "Question 3 - When should you give advice?"
              %select#question3{:name => "question3", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} After the speaker tells their story
                %option{:value => 0} Around halfway through the speaker's story
                %option{:value => 1} Never

            %div.question
              = label_tag :question4, "Question 4 - When is it acceptable to ask for personal information on the speaker?"
              %select#question4{:name => "question4", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} When the speaker says it's fine
                %option{:value => 0} When you think it's appropriate to ask e.g. after the speaker finishes speaking
                %option{:value => 1} Never

            %div.question
              = label_tag :question5, "Question 5 - What should a listener not do?"
              %select#question5{:name => "question5", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Be friendly at all times
                %option{:value => 1} Give advice and their opinion
                %option{:value => 0} Try to understand how the speaker feels

            %div.question
              = label_tag :question6, "Question 6 - What should you do if the speaker tells you that they plan on hurting themselves?"
              %select#question6{:name => "question6", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 1} Refer them to the suicide line and end the chat
                %option{:value => 0} Try to convince them to not do it
                %option{:value => 0} Continue the conversation and act like they didn't say anything

            %h.title.is-4 Scenario Questions
            %div.question
              = label_tag :question7, "Question 7 - What should you do if the speaker repeatedly asks for your personal information?"
              %select#question7{:name => "question7", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Give them the information they are seeking
                %option{:value => 0} Tell them incorrect information
                %option{:value => 1} Tell them to stop and if they persist then report them and end the chat

            %div.question
              = label_tag :question8, "Question 8 - What should you do if the speaker has not figured out a solution to their problem?"
              %select#question8{:name => "question8", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Try and keep them talking until they do find a solution
                %option{:value => 0} Direct the speaker to a different listener
                %option{:value => 1} Know that it's okay, my job isn't to solve their problem, and just being heard is powerful in itself

            %div.question
              = label_tag :question9, "Question 9 - What should you do if the chat isn't going too well and the speaker seem angered?"
              %select#question9{:name => "question9", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 1} Show empathy and kindness no matter what and ask them how you could support them
                %option{:value => 0} Immediately leave the chat without saying another word
                %option{:value => 0} Tell them your problems instead to calm them down

            %div.question
              = label_tag :question10, "Question 10 - What should you do if the speaker is harassing you?"
              %select#question10{:name => "question10", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Ignore their comments
                %option{:value => 1} Politely ask them to stop and if they don't then end the chat and report them
                %option{:value => 0} Tell them to stop and start harassing them back

            %div.question
              = label_tag :question11, "Question 11 - You are listening to a speaker talking about their experience. You start to feel anxious and upset. What should you do?"
              %select#question11{:name => "question11", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 1} Refer the speaker to another listener
                %option{:value => 0} Tell them to stop talking because it's making you upset
                %option{:value => 0} Quickly end the chat without saying a word

            %div.question
              = label_tag :question12, "Question 12 - You are listening to a speaker. What should you do if they're being unclear or you don't understand what they're saying?"
              %select#question12{:name => "question12", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Explain to them they are not speaking clearly and they need to be less ambiguous
                %option{:value => 0} Act like you understood what they said and hopefully, you can figure it out
                %option{:value => 1} Ask a question to clarify

            %div.question
              = label_tag :question13, "Question 13 - You are listening to a speaker. Why might it be a good reason for you to share a bit of your story with the speaker?"
              %select#question13{:name => "question13", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 1} To offer the speaker some hope that things can get better
                %option{:value => 0} To show the speaker that it could be a lot worse
                %option{:value => 0} To impress the speaker with how much you have gone through

            %div.question
              = label_tag :question14, "Question 14 -  You are listening to a speaker and you need to leave soon What should you do?"
              %select#question14{:name => "question14", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Don't mention it because it's rude to interrupt and then just leave when the time comes
                %option{:value => 1} Tell the speaker I need to leave soon and tell them the time you will leave
                %option{:value => 0} Just go offline

            %div.question
              = label_tag :question15, "Question 15 - You are listening to a speaker and they don't seem to be opening up. What should you do?"
              %select#question15{:name => "question15", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Tell them that you have probably heard worse stories
                %option{:value => 1} Know that it's okay because not everyone is going to instantly open up
                %option{:value => 0} Refer them to another listener and end the chat

            %div.question
              = label_tag :question16, "Question 16 - You are listening to a speaker and she is feeling discouraged because she hasn't found a job after months of searching. Which of the following thoughts would help you empathize with the speaker?"
              %select#question16{:name => "question16", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} I'm sure she will find something sooner than later
                %option{:value => 0} I was never this upset when I didn't have a job
                %option{:value => 1} I would also feel worried if I was in the same situation

            %div.question
              = label_tag :question17, "Question 17 - You are listening to a speaker and he tells you he did something that isn't illegal but really shocks you. You start to feel anger. What should you do?"
              %select#question17{:name => "question17", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Tell them what they did makes you feel very uncomfortable and they were wrong for doing that
                %option{:value => 1} So you can calm down, refer them to another listener and end the chat
                %option{:value => 0} Tell them to not talk about that situation and move on

            %div.question
              = label_tag :question18, "Question 18 - You are listening to a speaker and he talks about his problem and you seem to not be able to relate. What should you do?"
              %select#question18{:name => "question18", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Lie and make up a story to make it seem like you can relate
                %option{:value => 1} Say something like "I can't even imagine what that must feel like"
                %option{:value => 0} Say you can't chat anymore because you can't relate and refer them to another listener because they might be able to relate better

            %div.question
              = label_tag :question19, "Question 19 - You are listening to a speaker and they tell you that they need to leave but they haven't found a solution to their problem yet. What should you do?"
              %select#question19{:name => "question19", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 1} Tell them you understand and that it is ok to leave at any time
                %option{:value => 0} Try to get them to stay for a little bit longer
                %option{:value => 0} Give them explicit instructions about what they should do and how to do it

            %div.question
              = label_tag :question20, "Question 20 - You see someone harassing another user. What should you do?"
              %select#question20{:name => "question20", :onchange => "checkform()"}
                %option{:selected => "selected", :value => -1} -
                %option{:value => 0} Tell them to stop and tell them off
                %option{:value => 0} Ignore them because the user is able to report them
                %option{:value => 1} Report them so that the admins are aware of the user's activity

            = submit_tag "Submit answers", id: "submitbutton", disabled: true

app/views/home/twitter.html.haml
- content_for(:html_title) { 'MHS - Tweets For You' }
%section.section
  .container
    .columns.is-centered
      %h2.title.is-2.is-spaced Tweets We Picked For You
    - @tweets.each do |tweet|
      .box
        .media
          %article.media-left
            %figure.image.is-48x48
              = image_tag "#{tweet.user.profile_image_url}", class: "rounded-circle"
          .media-content
            .content
              %p
                %strong
                  = link_to "@#{tweet.user.name}", "https://twitter.com/#{tweet.user.screen_name}", target: :_blank
                %small
                  = link_to "View Tweet", "https://twitter.com/#{tweet.user.screen_name}/status/#{tweet.id}", target: :_blank
                %br
                = tweet.full_text

app/views/home/volunteer.html.haml
- content_for(:html_title) { 'MHS - Volunteer' }
%section.section
  .container
    .columns.is-centered
      .column.is-4
        %h2.title.is-2.is-spaced Volunteers Homepage
    %table.table.is-fullwidth
      %tr
        %th
          %p.subtitle.is-3 Training Questionaire
        -# If statement to change the button class to hidden could go here  
        %th= link_to 'Complete', 'questionnaire', {class: "button is-info is-rounded is-normal is-fullwidth"}
      %tr
        %th
          %p.subtitle.is-3 Edit Details
        %th= link_to 'Edit', edit_user_registration_path, {class: "button is-info is-rounded is-normal is-fullwidth"}
      %tr
        %th
          %p.subtitle.is-3 Logout of the session
        %th= button_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger is-rounded is-normal is-fullwidth"

app/views/home/volunteer_list.html.haml
- content_for(:html_title) { 'MHS - Volunteer List' }
%section.section
  .container
    .columns.is-centered
      .column.is-4
        %h2.title.is-2.is-spaced Volunteer List
    %table.table.is-fullwidth
      %tr
        %td.subtitle.is-3 Volunteer Name
        %td.subtitle.is-3 ID Verification
        %td.subtitle.is-3 Questionnaire
        -# lists through users who are volunteers and displays usernames
        - @users.each do |u|
          %tr
            %td= u.username
            %td
            %td