config/routes.rb
Rails.application.routes.draw do

  resources :channels
  root 'discussions#index'

  # Nested replies inside discussions
  resources :discussions do
    resources :replies, constraints: {onlyajax: true}
  end
  devise_for :users, controllers: { registrations: 'registrations'}

  # route for volunteers home page
  get "volunteer", to: "home#volunteer", as: :volunteer
  get "home", to: "home#index", as: :home_index
  get "admin", to: "home#admin", as: :admin
  get "volunteer_list", to: "home#volunteer_list", as: :volunteer_list
  get "twitter", to: "home#twitter", as: :twitter
  get "policy", to: "home#policy", as: :policy
  get "contact", to: "home#contact", as: :contact

  #post request for contact form
  post 'request_contact', to: 'home#request_contact'

  #report routes
  resources :reports, :only => [:index, :create]
  get "reports/reply", to: "reports#show_reply"
  get "reports/discussion", to: "reports#show_discussion"
  patch "reports", to: "reports#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route to the volunteer questionnaire
  get "questionnaire", to: "home#questionnaire"
  post "submit_questionnaire", to: "home#submit_questionnaire"

end

app/views/layouts/_footer.html.haml
%footer.footer.has-background-primary
  .content.has-text-centered.has-text-white
    %h1 © All rights reserved by Group 21
    .columns
      .column
        %h3.has-text-dark About Us
        %p.has-text-center.has-text-dark
          We are a small team of 6 trying to build a platform for people who want to talk about their mental health annonymously.
          We hope you feel safe and secure to talk about your feelings and experience in our platform.

      .column
        %h3.has-text-dark Our Website
        %ul
          %li
            %a{:href => "/twitter"} Twitter
          %li
            %a{:href => "/contact"} Contact
          %li
            %a{:href => "/users/sign_up"} Sign Up
          %li
            %a{:href => "/policy"} Policy
      .column
        %h3.has-text-dark Good links to visit
        %ul
          %li
            %a{:href => "https://www.supportline.org.uk/problems/suicide/"} Support Line
          %li
            %a{:href => "https://www.nhs.uk/mental-health/"} NHS Mental Health
          %li
            %a{:href => "https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/behaviours/help-for-suicidal-thoughts/"} NHS Sucidide Line
          %li
            %a{:href => "https://www.mind.org.uk/information-support/guides-to-support-and-services/seeking-help-for-a-mental-health-problem/where-to-start/"} Mind.org

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for?(:html_title) ? yield(:html_title) : "MHS"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('MHS-Logo.png')

  %body
    - if flash[:notice]
      .notification.is-success.global-notification
        %p.notice= notice
    - if flash[:alert]
      .notification.is-danger.global-notification
        %p.alert= alert
    %nav.navbar.is-light{"aria-label" => "main navigation", role: "navigation"}
      .navbar-brand
        = link_to root_path, class:"navbar-item" do
          %h1.title.is-5 Discussions
        .navbar-burger.burger{"data-target" => "navbar"}
          %span
          %span
          %span
      #navbar.navbar-menu
        .navbar-end
          - if user_signed_in?
            .navbar-item
              .field.is-grouped
                = link_to 'New Discussion', new_discussion_path, class:"button is-info"
                = link_to "Twitter", twitter_path, class: "button is-light"
                = link_to "Contact", contact_path, class: "button is-light"  
            .navbar-item.has-dropdown.is-hoverable
              = link_to 'Account', edit_user_registration_path, class: "navbar-link"
              .navbar-dropdown.is-right
                -# If statement to take the user to home controller, index action
                = link_to current_user.username, home_index_path, class:"navbar-item"
                = link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item"
          - else
            .navbar-item
              .field.is-grouped
                %p.control
                  = link_to 'New Discussion', new_discussion_path, class:"button is-info"
                %p.control
                  = link_to "Twitter", twitter_path, class: "button is-light"
                %p.control
                  = link_to "Sign In", new_user_session_path, class: "button is-light"
                %p.control
                  = link_to "Sign up", new_user_registration_path, class: "button is-light"
                %p.control
                  = link_to "Contact", contact_path, class: "button is-light"  
    %section.section
      .container
        = yield

    -# Renders the footer partial
    = render "layouts/footer"